### ISSUE TITLE
One faulty SVG breaks the whole Gulp task

### ISSUE THREAD

**Issue by MarcoDeT** [corneliusio/gulp-svgo#7]
Hi,
I noticed that when I run my gulp task and one SVG is syntactically wrong, then the svgo plugin breaks the task because the promise rejection is not handled with catch(). It would be nice if you could fix it. Here you have a screenshot containing the error.

![unhandled_error_in_svgo_pipe](https://user-images.githubusercontent.com/20768947/49753070-8d4fde00-fcb2-11e8-8eb9-5b1cab9402d1.png)

It would also be nice to know which file originates the error so that I don't have to look for it because it's difficult to find exactly that wrong one between hundreds of svgs.

**Comment by corneliusio** [comment]
Good catch (no pun intended). I'll take a look at this as soon as possible this week.

**Comment by corneliusio** [comment]
Errors from SVGO should now be properly passed along to gulp, and I've also made sure to include the filename that originated the error for easier debugging. Go ahead and check it out in the new 2.0.0 release (note that node@4 is no longer supported). If there's some behavior here you'd like to see tweaked feel free to open up another issue!

**Comment by MarcoDeT** [comment]
Thank you for your effort. I'll check it out. No problem that it doesn't work with node@4. I'm working with node@10.
