### ISSUE TITLE
TypeError in Catch Callback

### ISSUE THREAD

**Issue by MarcoDeT** [corneliusio/gulp-svgo#8]
Hi,
When I run the plugin and the catch callback is executed, a TypeError occurs.
I suppose that the thrown error doesn't have a message property because SVGO throws a string.
Below you see the output of the TypeError.

![2018-12-19 14_16_31-test svg - am-default - visual studio code](https://user-images.githubusercontent.com/20768947/50222830-bf8bca80-0399-11e9-9793-37a4ffde9472.png)

Furthermore, I have a question that relates to the error handling. Why does the gulp plugin forward a plugin error? The problem with that behaviour is that it breaks the gulp task. I think it's sufficient to log the error and then just call next(null) or next().

**Comment by corneliusio** [comment]
That is really odd about the TypeError, I always get an error object from SVGO and I tested this myself with real files as well as having the tests set up for malformed svg handling.

However, I can understand why you'd prob want the error to simply be logged without being passed along to Gulp, only did that since it seems to be the way Gulp wants errors to be handled. Though, I suppose Gulp would also expect me to throw an error if the file being passed to the plugin wasn't svg, ha. I'll tweak this around and push an update here in a bit.

**Comment by corneliusio** [comment]
I've pushed another update up, see if the new behavior is more in line with what you'd like to see.

**Comment by MarcoDeT** [comment]
> That is really odd about the TypeError, I always get an error object from SVGO and I tested this myself with real files as well as having the tests set up for malformed svg handling.
> 
I didn't know that SVGO usually throws an error object. You're right, it's really odd that the datatype can vary.

> However, I can understand why you'd prob want the error to simply be logged without being passed along to Gulp
> 
The reason is that if I have 10 malformed svgs, then I can fix them all at once. Otherwise I have to run the build task 10 times until I've fixed all the malformed svgs because the gulp task is stopped if an error is passed along to Gulp.

> Though, I suppose Gulp would also expect me to throw an error if the file being passed to the plugin wasn't svg, ha.
> 
In my opinion, it depends on the plugin's design. If you expect that the gulp task only handles svgs, then your plugin must behave as you suggested. Otherwise the current behaviour is ok.

**Comment by MarcoDeT** [comment]
> I've pushed another update up, see if the new behavior is more in line with what you'd like to see.
> 
Ok I'll take a look at it.

**Comment by MarcoDeT** [comment]
This update is excellent. Many thanks for your efforts.
